import type { Metadata } from "next/types";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./styles/globals.css";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "./theme";

export const metadata: Metadata = {
  title: "Song Lyrics Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
